name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/apps/-Synexis_Technologies_Web_Site

            git pull origin main

            # Inject Environment Variables from GitHub Secrets
            echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" > .env.local
            echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env.local

            npm install

            npm run build

            pm2 restart synexis-web